version: '3.5'

services:
  php-apache:
    build: .
    image: alexandregv/garradin
    restart: unless-stopped
    volumes:
      - data:/var/www/garradin/data/:rw
      - ./config.local.php:/var/www/garradin/config.local.php:rw
    environment:
      TZ: Europe/Paris
    labels:
      traefik.enable: 'true'
      traefik.docker.network: 'traefik'
      traefik.http.services.garradin.loadbalancer.server.port: '80'
      traefik.http.routers.garradin.entrypoints: 'https'
      traefik.http.routers.garradin.rule: 'Host(`garradin.asso.fr`)'
      traefik.http.routers.garradin.tls: 'true'
    networks:
      - traefik

networks:
  traefik:
    external: true

volumes:
  data:
